"""add document ocr page count

Revision ID: 19373f9bd02a
Revises: 569d1b72d580
Create Date: 2026-09-12 14:08:52.714044
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '19373f9bd02a'
down_revision: str | None = '569d1b72d580'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ocr_page_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ocr_page_count')
    # ### end Alembic commands ###
