"""add document map model

Revision ID: 476776c615f9
Revises: 7b1914311efd
Create Date: 2026-09-13 10:53:36.131225
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '476776c615f9'
down_revision: str | None = '7b1914311efd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('map_model', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'map_model')
    # ### end Alembic commands ###
