"""add document error code

Revision ID: 569d1b72d580
Revises: 952757ab67fb
Create Date: 2026-09-12 14:02:32.442385
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '569d1b72d580'
down_revision: str | None = '952757ab67fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('error_code', sa.String(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_code')
    # ### end Alembic commands ###
