"""add node assistant intent fields

Revision ID: 7b1914311efd
Revises: 19373f9bd02a
Create Date: 2026-09-13 10:31:00.141085
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7b1914311efd'
down_revision: str | None = '19373f9bd02a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('intent', sa.String(length=32), server_default='ask', nullable=False))
    op.add_column('questions', sa.Column('answer_payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answer_payload')
    op.drop_column('questions', 'intent')
    # ### end Alembic commands ###
