"""add rag pipeline tables

Revision ID: 952757ab67fb
Revises: 
Create Date: 2026-09-12 13:44:38.098444
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '952757ab67fb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('paragraph_count', sa.Integer(), nullable=True),
    sa.Column('tree_status', sa.String(length=32), nullable=False),
    sa.Column('tree_error', sa.Text(), nullable=True),
    sa.Column('tree_mode', sa.String(length=32), nullable=True),
    sa.Column('tree_built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_content_chunks_document_index')
    )
    op.create_index(op.f('ix_content_chunks_document_id'), 'content_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_content_chunks_section_index'), 'content_chunks', ['section_index'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('path', sa.String(length=64), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_document_id'), 'knowledge_nodes', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_parent_id'), 'knowledge_nodes', ['parent_id'], unique=False)
    op.create_table('evidence_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('source_section_index', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['content_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_links_chunk_id'), 'evidence_links', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_document_id'), 'evidence_links', ['document_id'], unique=False)
    op.create_index('ix_evidence_links_target', 'evidence_links', ['target_type', 'target_id'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parent_node_id', sa.Uuid(), nullable=False),
    sa.Column('child_node_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_edges_child_node_id'), 'knowledge_edges', ['child_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_document_id'), 'knowledge_edges', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_parent_node_id'), 'knowledge_edges', ['parent_node_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answer_mode', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_document_id'), 'questions', ['document_id'], unique=False)
    op.create_index(op.f('ix_questions_node_id'), 'questions', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_node_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_document_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_knowledge_edges_parent_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_document_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_child_node_id'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index('ix_evidence_links_target', table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_document_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_chunk_id'), table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_knowledge_nodes_parent_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_document_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_content_chunks_section_index'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_document_id'), table_name='content_chunks')
    op.drop_table('content_chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
